name: STM32 CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install ARM GCC and Cppcheck
      run: |
        sudo apt update
        sudo apt install -y gcc-arm-none-eabi make cppcheck

    - name: Static Analysis with Cppcheck
      run: |
        cppcheck --enable=warning,performance,portability,information \
        --inconclusive \
        --suppress=missingIncludeSystem \
        --suppress=unusedFunction \
        Core/Src

    - name: Build STM32 Firmware
      run: make all_build   # ‚Üê changed from 'all'

    - name: Upload Firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: |
          *.elf
          *.bin
          *.hex
