name: STM32 CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code
    - uses: actions/checkout@v4

    # 2️⃣ Install ARM GCC + Cppcheck
    - name: Install ARM GCC and Cppcheck
      run: |
        sudo apt update
        sudo apt install -y gcc-arm-none-eabi make cppcheck

    # 3️⃣ Static Analysis (application code only)
    - name: Static Analysis with Cppcheck
      run: |
        cppcheck --enable=warning,performance,portability,information \
        --inconclusive \
        --suppress=missingIncludeSystem \
        --suppress=unusedFunction \
        Core/Src

    # 4️⃣ Build firmware (Debug folder)
    - name: Build STM32 Firmware
      run: |
        cd Debug
        make

    # 5️⃣ Upload firmware artifacts
    - name: Upload Firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: |
          Debug/*.elf
          Debug/*.bin
          Debug/*.hex
