name: STM32 Windows Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install ARM GCC
      run: choco install -y gcc-arm-embedded make
      shell: powershell

    - name: Build STM32 Firmware
      run: |
        cd Debug
        make
      shell: powershell

    - name: Upload Firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: |
          Debug/*.elf
          Debug/*.bin
          Debug/*.hex
