name: STM32 Windows Build Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install ARM GCC and make
      run: choco install -y gcc-arm-embedded make
      shell: powershell

    - name: Build Firmware
      run: |
        # Build in Debug folder
        cd Debug
        make

        # List files to confirm
        dir

      shell: powershell

    - name: Upload Firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: |
          Debug\*.elf
          Debug\*.bin
          Debug\*.hex
